name: Sync Private to Public Repo

on:
  push:
    branches:
      - main  # Sync only the main branch

permissions:
  contents: write  # Ensure the workflow can push to repositories

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout private repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add public repository as a remote
        run: git remote add public https://github.com/FlyingToasters3641/FlyingToasters2025Public.git

      - name: Push to public repository
        env:
          PUBLIC_REPO_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
        run: |
          git push https://$PUBLIC_REPO_TOKEN@github.com/FlyingToasters3641/FlyingToasters2025Public.git main --force
